### ISSUE TITLE
alternative uses?

### ISSUE THREAD

**Issue by xstalpha** [WhiteLabelDev/phpGab#1]
powerful tool! are there any alternative uses?

**Comment by wldpaul** [comment]
The majority of other tools out there expect you to gain the API token through some other method and leave it down to the user; so aren't really that useful. As this tool will retrieve your token automatically from your regular login details it makes it much easier and quicker to get started. When you have the token you could do many things with it, not just post Gabs. You could use it to follow other Gabbers, search for Gabs matching keywords and more. When you have the token that's the easy bit; and left to other developers to implement. It should be quite trivial if you know the endpoint from the docs.
